name: Run Python Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'   # or your version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest       # if using pytest
          # pip install -r requirements.txt  # if you have one

      - name: Run tests
        run: |
          pytest test_app.py
